version: '3'
services:
    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:
        - ss_data:/home/docker/code
        depends_on:
        - app

    app:
        container_name: app-container
        build: ./django-todo
        restart: always
        command: uwsgi --ini service-uwsgi.ini
        volumes:
        - ss_data:/home/docker/code

volumes:
    ss_data:
